name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x Sector-KML-App/android/gradlew

    - name: Build with Gradle
      run: ./gradlew clean assembleDebug --no-build-cache
      working-directory: Sector-KML-App/android

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: "**/build/outputs/apk/debug/*.apk"
        if-no-files-found: error
